### ISSUE TITLE
Broadcaster (ec2 -> RTMP) has visible Firefox/Microphone watermarks

### ISSUE THREAD

**Issue by snwbrdr78** [aws-samples/amazon-chime-live-events#3] opened 2020-06-26 21:41 UTC
Branch:  39b1fc8

The broadcaster displays a Firefox logo and microphone logo in the top/middle of the screen (see below).  I think the microphone would be removed, if the browser didn't ask for it/activate it.

Not sure about how to remove the Firefox logo when fullscreen.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/51972467/85903199-9d5ae000-b7ba-11ea-90ce-c64fd6b2b12d.png">

**Comment by nicklera1** [comment] 2020-12-15 18:39
I seem to unable to reproduce this issue might be limited to Firefox version.  Resolving for now! Feel free to re-open if still experiencing the issue. Please also provide the version of FF used.

**Closed as completed by nicklera1** 2020-12-15 18:39 UTC
Labels: triaged

**Comment by pranjal-goswami** [comment] 2020-12-22 06:02
Hi, 
We see the firefox logo on the stream as well. 
![image](https://user-images.githubusercontent.com/1142904/102854704-10cb6a80-4449-11eb-91ee-c3d8ba9c9cbb.png)

We are using the deploy script provided in the serverless cloud formation. (Deployed just a week ago)

The Dockerfile installs the latest release of Firefox for Debian, so I assume it would be 84.

```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN /usr/bin/apt-get update
RUN /usr/bin/apt-get upgrade -y
RUN /usr/bin/apt-get install -y pulseaudio xvfb firefox ffmpeg xdotool curl unzip

COPY run.sh /
RUN chmod +x /run.sh

ENTRYPOINT ["/run.sh"]
```

Let me know if there is a fix for this.

**Comment by dimabory** [comment] 2021-04-28 15:57
@pranjal-goswami If you're still willing to find a solution please check out #36
